# This is a basic workflow to help you get started with Actions

name: Update Readme

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "*/60 12 * * 1"
    - cron: "*/60 12 * * 5"
    - cron: "*/60 12 * * 3"
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Download Waka-stats SVG
        uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          url: ${{ secrets.WAKA_SVG }}
          dir: "./assets"
          filename: "waka-langs.svg"
          
      - name: Download Waka-stats SVG 2
        uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          url: ${{ secrets.WAKA_SVG_2 }}
          dir: "./assets"
          filename: "waka-activs.svg"

      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          header: "Welcome to my Github! 👋"
          subhead: "Just a student who codes. Member of ACM."
          footer: "![Wakatime-Stats-SVG](assets/waka-stats.svg)"
          customReadmeFile: |
            ## ${header}

            ${subhead}
            
            ### My Coding Metrics
            
            ---
            
            <!--START_SECTION:waka-->
            
            <!--END_SECTION:waka-->

            <p align="center" >
            <img width="49%" alt="My most used Languages" src="assets/waka-langs.svg"/>
            <img width="49%" alt="My activity over last month" src="assets/waka-activs.svg"/>
            </p>
              
      - name: Insert Waka Metrics
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_OS: False
          COMMIT_BY_ME: False
          SHOW_LINES_OF_CODE: False
          SHOW_PROFILE_VIEWS: False
          SHOW_LANGUAGE_PER_REPO: False
          
          


