# This is a basic workflow to help you get started with Actions

name: Update Readme

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "*/10 * * * *"
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "Welcome to my Github! 👋"
          subhead: "Just a student who codes. KU Undergrad"
          footer: "![https://wakatime.com/share/@mkeleti/b8955317-c0b7-4283-81eb-d6417af927d6.png](https://wakatime.com/share/@mkeleti/b8955317-c0b7-4283-81eb-d6417af927d6.png)"
          customReadmeFile: |
            ## ${header}

            ${subhead}

            ---
            
            <!--START_SECTION:waka-->
            
            <!--END_SECTION:waka-->
            
            ---

            ${footer}

          
